name: theme_tailor_annotation
description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
# dependencies:
# flutter:
#   sdk: flutter
