name: theme_tailor_annotation
description: >
  Annotations for the Theme Tailor code-generator.
  This package does nothing without Theme Tailor.
version: 0.0.1
homepage: https://github.com/Iteo/theme_tailor
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0
