name: example
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter

  theme_tailor_annotation: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  theme_tailor:
    path: ../.

flutter:
  uses-material-design: true
