name: theme_tailor
description: >
  Theme Tailor. Utility for generating themes, Flutter's ThemeExtension classes and extensions 
  on BuildContext and ThemeData to access themes
version: 1.0.0
repository: https://github.com/Iteo/theme_tailor
issue_tracker: https://github.com/Iteo/theme_tailor/issues
homepage: https://github.com/Iteo/theme_tailor
documentation: https://github.com/Iteo/theme_tailor/blob/main/packages/theme_tailor/README.md

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=3.0.0 <5.0.0"
  build: ^2.3.0
  build_config: ^1.0.0
  meta: ^1.7.0
  source_gen: ^1.2.2
  theme_tailor_annotation: ^1.0.0
  source_helper: ^1.3.2

dev_dependencies:
  build_runner: ^2.1.11
  lint: ^1.8.2
  source_gen_test: ^1.0.3
  test: ^1.21.1
