name: theme_tailor
description: Theme Tailor generator. Theming utility
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  analyzer: ^4.1.0
  build: ^2.3.0
  build_config: ^1.0.0
  collection: ^1.16.0
  meta: ^1.7.0
  source_gen: ^1.2.2
  theme_tailor_annotation:
    path: ../theme_tailor_annotation
  source_helper: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  lint: ^1.8.2
  source_gen_test: ^1.0.3
  test: ^1.21.1
