name: theme_tailor
description: >
  Code generator and theming utility for supercharging and embracing Flutter's 3.0
  ThemeExtension classes. The generator can create themes based on the lists of the theme properties. 
  Additionally, you can generate extensions on BuildContext and ThemeData to ease out access 
  to the theming classes.
version: 1.0.1
repository: https://github.com/Iteo/theme_tailor
issue_tracker: https://github.com/Iteo/theme_tailor/issues
homepage: https://github.com/Iteo/theme_tailor
documentation: https://github.com/Iteo/theme_tailor/blob/main/packages/theme_tailor/README.md

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=3.0.0 <5.0.0"
  build: ^2.3.0
  build_config: ^1.0.0
  collection: ^1.16.0
  meta: ^1.7.0
  source_gen: ^1.2.2
  theme_tailor_annotation: ^1.0.0
  source_helper: ^1.3.2

dev_dependencies:
  lint: ^1.8.2
  source_gen_test: ^1.0.3
  test: ^1.21.1
